from __future__ import annotations

from pathlib import Path

from ast_program import (
    ASTNode,
    ASTProgram,
)

from program_architecture import (
    ProgramArchitecture,
)

from evolved_language import EvolvedLanguage


class PythonEmitter:

    INDENT = "    "

    def __init__(
        self,
        output_directory: str = "generated",
    ) -> None:

        self.output_directory = Path(
            output_directory
        )

    def _function_name(
        self,
        function_id: str,
    ) -> str:

        if (
            not function_id
            or not function_id.startswith("F")
            or not function_id[1:].isdigit()
        ):

            raise ValueError(
                "Invalid evolved function id."
            )

        return (
            f"evolved_"
            f"{function_id.lower()}"
        )

    def _opcode_name(
        self,
        opcode_id: str,
    ) -> str:

        if (
            not opcode_id
            or not opcode_id.startswith("O")
            or not opcode_id[1:].isdigit()
        ):

            raise ValueError(
                "Invalid evolved opcode id."
            )

        return (
            f"evolved_"
            f"{opcode_id.lower()}"
        )

    # =====================================================
    # PUBLIC API
    # =====================================================

    def emit_program(
        self,
        program: ASTProgram,
        module_name: str,
    ) -> Path:

        if program.root is None:

            raise ValueError(
                "AST program has no root."
            )

        source = self.render_program(
            program
        )

        self.output_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        path = (
            self.output_directory
            / f"{module_name}.py"
        )

        path.write_text(
            source,
            encoding="utf-8",
        )

        return path

    def emit_architecture(
        self,
        architecture: ProgramArchitecture,
        module_name: str,
        evolved_language: EvolvedLanguage | None = None,
    ) -> Path:

        source = (
            self.render_architecture(
                architecture,
                evolved_language,
            )
        )

        self.output_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        path = (
            self.output_directory
            / f"{module_name}.py"
        )

        path.write_text(
            source,
            encoding="utf-8",
        )

        return path

    def render_program(
        self,
        program: ASTProgram,
    ) -> str:

        if program.root is None:

            raise ValueError(
                "AST program has no root."
            )

        body = self._render_node(
            program.root,
            variable_name="value",
            indent_level=1,
        )

        lines = [
            '"""',
            "Automatically generated by Project EVOLVE.",
            "",
            "Do not edit manually.",
            '"""',
            "",
            "",
            "def evolved_program(",
            "    input_value: float,",
            "    context_id: int,",
            "    runtime,",
            ") -> float:",
            "",
            "    value = float(input_value)",
        ]

        lines.extend(
            body
        )

        lines.extend(
            [
                "",
                "    return value",
                "",
            ]
        )

        return "\n".join(
            lines
        )

    def render_architecture(
        self,
        architecture: ProgramArchitecture,
        evolved_language: EvolvedLanguage | None = None,
    ) -> str:

        if architecture.main.root is None:

            raise ValueError(
                "Architecture MAIN has no root."
            )

        lines = [
            '"""',
            (
                "Automatically generated by "
                "Project EVOLVE."
            ),
            "",
            "Do not edit manually.",
            '"""',
            "",
            "",
        ]

        # =================================================
        # EVOLVED OPCODES
        # =================================================

        if evolved_language is not None:

            for opcode_id in sorted(
                evolved_language.opcodes
            ):

                opcode = (
                    evolved_language
                    .opcodes[
                        opcode_id
                    ]
                )

                if opcode.program.root is None:

                    raise ValueError(
                        "Evolved opcode has no root."
                    )

                python_name = (
                    self._opcode_name(
                        opcode_id
                    )
                )

                lines.extend(
                    [
                        f"def {python_name}(",
                        "    value: float,",
                        "    context_id: int,",
                        "    runtime,",
                        "    call_depth: int,",
                        "    function_stack: list[str],",
                        "    opcode_stack: list[str],",
                        ") -> float:",
                        "",
                        (
                            "    opcode_stack = "
                            "runtime.enter_evolved_opcode("
                        ),
                        f"        {opcode_id!r},",
                        "        call_depth,",
                        "        opcode_stack,",
                        "    )",
                        "",
                    ]
                )

                body = (
                    self._render_architecture_node(
                        node=opcode.program.root,
                        variable_name="value",
                        indent_level=1,
                        architecture=architecture,
                        evolved_language=evolved_language,
                    )
                )

                lines.extend(body)

                lines.extend(
                    [
                        "",
                        "    return value",
                        "",
                        "",
                    ]
                )

        # =================================================
        # EVOLVED HELPER FUNCTIONS
        # =================================================

        for function_id in sorted(
            architecture.functions
        ):

            function = (
                architecture.functions[
                    function_id
                ]
            )

            if function.program.root is None:

                raise ValueError(
                    "Evolved function has no root."
                )

            python_name = (
                self._function_name(
                    function_id
                )
            )

            lines.extend(
                [
                    f"def {python_name}(",
                    "    value: float,",
                    "    context_id: int,",
                    "    runtime,",
                    "    call_depth: int,",
                    "    function_stack: list[str],",
                    "    opcode_stack: list[str],",
                    ") -> float:",
                    "",
                    (
                        "    function_stack = "
                        "runtime.enter_evolved_function("
                    ),
                    f"        {function_id!r},",
                    "        call_depth,",
                    "        function_stack,",
                    "    )",
                    "",
                ]
            )

            body = (
                self._render_architecture_node(
                    node=function.program.root,
                    variable_name="value",
                    indent_level=1,
                    architecture=architecture,
                    evolved_language=evolved_language,
                )
            )

            lines.extend(body)

            lines.extend(
                [
                    "",
                    "    return value",
                    "",
                    "",
                ]
            )

        # =================================================
        # MAIN
        # =================================================

        lines.extend(
            [
                "def evolved_program(",
                "    input_value: float,",
                "    context_id: int,",
                "    runtime,",
                ") -> float:",
                "",
                "    value = float(input_value)",
                "    call_depth = 0",
                "    function_stack: list[str] = []",
                "    opcode_stack: list[str] = []",
                "",
            ]
        )

        main_body = (
            self._render_architecture_node(
                node=architecture.main.root,
                variable_name="value",
                indent_level=1,
                architecture=architecture,
                evolved_language=evolved_language,
            )
        )

        lines.extend(
            main_body
        )

        lines.extend(
            [
                "",
                "    return value",
                "",
            ]
        )

        return "\n".join(
            lines
        )

    # =====================================================
    # AST -> PYTHON
    # =====================================================

    def _render_node(
        self,
        node: ASTNode,
        variable_name: str,
        indent_level: int,
    ) -> list[str]:

        indent = (
            self.INDENT
            * indent_level
        )

        node_type = node.node_type

        step_line = (
            f"{indent}runtime.ast_step()"
        )

        # -------------------------------------------------
        # SEQUENCE
        # -------------------------------------------------

        if node_type == "SEQUENCE":

            lines: list[str] = [
                step_line
            ]

            for child in node.children:

                lines.extend(
                    self._render_node(
                        child,
                        variable_name,
                        indent_level,
                    )
                )

            return lines

        # -------------------------------------------------
        # ADD
        # -------------------------------------------------

        if node_type == "ADD":

            if node.value is None:

                raise ValueError(
                    "ADD node has no value."
                )

            return [
                step_line,
                (
                    f"{indent}{variable_name} "
                    f"+= {float(node.value)!r}"
                ),
            ]

        # -------------------------------------------------
        # SUBTRACT
        # -------------------------------------------------

        if node_type == "SUBTRACT":

            if node.value is None:

                raise ValueError(
                    "SUBTRACT node has no value."
                )

            return [
                step_line,
                (
                    f"{indent}{variable_name} "
                    f"-= {float(node.value)!r}"
                ),
            ]

        # -------------------------------------------------
        # MULTIPLY
        # -------------------------------------------------

        if node_type == "MULTIPLY":

            if node.value is None:

                raise ValueError(
                    "MULTIPLY node has no value."
                )

            return [
                step_line,
                (
                    f"{indent}{variable_name} "
                    f"*= {float(node.value)!r}"
                ),
            ]

        # -------------------------------------------------
        # ABS
        # -------------------------------------------------

        if node_type == "ABS":

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    f"abs({variable_name})"
                ),
            ]

        # -------------------------------------------------
        # IF_CONTEXT
        # -------------------------------------------------

        if node_type == "IF_CONTEXT":

            if node.context is None:

                raise ValueError(
                    "IF_CONTEXT node has no context."
                )

            lines = [
                step_line,
                (
                    f"{indent}if context_id "
                    f"== {int(node.context)}:"
                ),
            ]

            if not node.children:

                lines.append(
                    (
                        f"{indent}"
                        f"{self.INDENT}"
                        "pass"
                    )
                )

                return lines

            # Genome._execute_ast_node() yalnızca
            # children[0] çalıştırıyor.
            #
            # Generated Python aynı semantiği
            # birebir takip etmeli.

            lines.extend(
                self._render_node(
                    node.children[0],
                    variable_name,
                    indent_level + 1,
                )
            )

            return lines

        # -------------------------------------------------
        # CALL_LEGACY_MAIN
        # -------------------------------------------------

        if node_type == "CALL_LEGACY_MAIN":

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    "runtime.call_legacy_main("
                    f"{variable_name}, "
                    "context_id"
                    ")"
                ),
            ]

        # -------------------------------------------------
        # CALL_MODULE
        # -------------------------------------------------

        if node_type == "CALL_MODULE":

            if node.module_id is None:

                raise ValueError(
                    "CALL_MODULE node has no module_id."
                )

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    "runtime.call_module("
                    f"{node.module_id!r}, "
                    f"{variable_name}, "
                    "context_id"
                    ")"
                ),
            ]

        # -------------------------------------------------
        # CALL_MACRO
        # -------------------------------------------------

        if node_type == "CALL_MACRO":

            if node.macro_id is None:

                raise ValueError(
                    "CALL_MACRO node has no macro_id."
                )

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    "runtime.call_macro("
                    f"{node.macro_id!r}, "
                    f"{variable_name}, "
                    "context_id"
                    ")"
                ),
            ]

        # -------------------------------------------------
        # UNKNOWN NODE
        # -------------------------------------------------

        raise ValueError(
            "Unsupported AST node type: "
            f"{node_type}"
        )

    def _render_architecture_node(
        self,
        node: ASTNode,
        variable_name: str,
        indent_level: int,
        architecture: ProgramArchitecture,
        evolved_language: EvolvedLanguage | None = None,
    ) -> list[str]:

        indent = (
            self.INDENT
            * indent_level
        )

        node_type = node.node_type

        step_line = (
            f"{indent}runtime.ast_step()"
        )

        # =================================================
        # SEQUENCE
        # =================================================

        if node_type == "SEQUENCE":

            lines = [
                step_line
            ]

            for child in node.children:

                lines.extend(
                    self._render_architecture_node(
                        node=child,
                        variable_name=variable_name,
                        indent_level=indent_level,
                        architecture=architecture,
                        evolved_language=evolved_language,
                    )
                )

            return lines

        # =================================================
        # PRIMITIVES
        # =================================================

        if node_type == "ADD":

            return [
                step_line,
                (
                    f"{indent}{variable_name} "
                    f"+= {float(node.value)!r}"
                ),
            ]

        if node_type == "SUBTRACT":

            return [
                step_line,
                (
                    f"{indent}{variable_name} "
                    f"-= {float(node.value)!r}"
                ),
            ]

        if node_type == "MULTIPLY":

            return [
                step_line,
                (
                    f"{indent}{variable_name} "
                    f"*= {float(node.value)!r}"
                ),
            ]

        if node_type == "ABS":

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    f"abs({variable_name})"
                ),
            ]

        # =================================================
        # IF_CONTEXT
        # =================================================

        if node_type == "IF_CONTEXT":

            lines = [
                step_line,
                (
                    f"{indent}if context_id "
                    f"== {int(node.context)}:"
                ),
            ]

            if not node.children:

                lines.append(
                    (
                        f"{indent}"
                        f"{self.INDENT}"
                        "pass"
                    )
                )

                return lines

            # Interpreter yalnız children[0].
            lines.extend(
                self._render_architecture_node(
                    node=node.children[0],
                    variable_name=variable_name,
                    indent_level=(
                        indent_level + 1
                    ),
                    architecture=architecture,
                    evolved_language=evolved_language,
                )
            )

            return lines

        # =================================================
        # EVOLVED FUNCTION
        # =================================================

        if node_type == "CALL_FUNCTION":

            function_id = (
                node.function_id
            )

            if (
                function_id is None
                or function_id
                not in architecture.functions
            ):

                return [
                    step_line,
                    (
                        f"{indent}raise RuntimeError("
                        "'Invalid evolved function call.'"
                        ")"
                    ),
                ]

            python_name = (
                self._function_name(
                    function_id
                )
            )

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    f"{python_name}("
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    f"{variable_name},"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "context_id,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "runtime,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "call_depth + 1,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "function_stack,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "opcode_stack,"
                ),
                f"{indent})",
            ]

        # =================================================
        # EVOLVED OPCODE
        # =================================================

        if node_type == "CALL_OPCODE":

            opcode_id = (
                node.opcode_id
            )

            if (
                opcode_id is None
                or evolved_language is None
                or opcode_id
                not in evolved_language.opcodes
            ):

                return [
                    step_line,
                    (
                        f"{indent}raise RuntimeError("
                        "'Invalid evolved opcode call.'"
                        ")"
                    ),
                ]

            python_name = (
                self._opcode_name(
                    opcode_id
                )
            )

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    f"{python_name}("
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    f"{variable_name},"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "context_id,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "runtime,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "call_depth + 1,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "function_stack,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "opcode_stack,"
                ),
                f"{indent})",
            ]

        # =================================================
        # LEGACY MAIN
        # =================================================

        if node_type == "CALL_LEGACY_MAIN":

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    "runtime.call_legacy_main("
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    f"{variable_name},"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "context_id,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "call_depth + 1,"
                ),
                f"{indent})",
            ]

        # =================================================
        # MODULE
        # =================================================

        if node_type == "CALL_MODULE":

            if node.module_id is None:

                raise ValueError(
                    "CALL_MODULE node has no module_id."
                )

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    "runtime.call_module("
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    f"{node.module_id!r},"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    f"{variable_name},"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "context_id,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "call_depth + 1,"
                ),
                f"{indent})",
            ]

        # =================================================
        # MACRO
        # =================================================

        if node_type == "CALL_MACRO":

            if node.macro_id is None:

                raise ValueError(
                    "CALL_MACRO node has no macro_id."
                )

            return [
                step_line,
                (
                    f"{indent}{variable_name} = "
                    "runtime.call_macro("
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    f"{node.macro_id!r},"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    f"{variable_name},"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "context_id,"
                ),
                (
                    f"{indent}"
                    f"{self.INDENT}"
                    "call_depth + 1,"
                ),
                f"{indent})",
            ]

        raise ValueError(
            "Unsupported architecture AST node: "
            f"{node_type}"
        )
